### ISSUE TITLE
intergration

### ISSUE THREAD

**Issue by therealelyayo** [dirkhe1051931999/quasar-typescript-admin-template#11]
hello awesome work but i would like to know if i can add my previous sql table to this and modify tables accordingly help would be very much rewarded

**Comment by dirkhe1051931999** [comment]
> hello awesome work but i would like to know if i can add my previous sql table to this and modify tables accordingly help would be very much rewarded

hi，it is a mock server by nodejs , not use database

**Comment by xalteropsx** [comment]
how can we sign in @dirkhe1051931999  plz help do i need to remove thise code email and sms ?
