### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by KivenCkl** [dirkhe1051931999/quasar-typescript-admin-template#17]
These dependencies were not found:

* codeMirror in ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!./node_modules/ts-loader??ref--2-0!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/convert/index.vue?vue&type=script&lang=ts&, ./src/utils/cssConvert.js
* pages/dashboard/index.vue in ./src/router/routes.ts

To install them, you can run: npm install --save codeMirror pages/dashboard/index.vue

I tried to install codeMirror, but it doesn't work. My node version is v14.15.3, quasar v1.2.0

**Comment by dirkhe1051931999** [comment]
sorry  I  just saw the message
remove node_modules and install again confirm your network is ok 
I can npm  run dev it and build it

**Comment by dirkhe1051931999** [comment]
rename pages/dashboard/Index.vue  ->  pages/dashboard/index.vue     lower case problem
